### ISSUE TITLE
Error in designfilt

### ISSUE THREAD

**Issue by NinaOmejc** [MariusKlug/zapline-plus#24]
Hi,
thank you for a great toolbox. However, somehow I get an error using it.

I have EEGLAB v2023.1, zapline-plus version 1.2.1 (latest, installed through EEGLAB), signal processing toolbox installed. It is using functions in `.\MATLAB\R2023a\toolbox\signal\signal\*` I checked data have no nans and the sampling rate is 250 Hz. I call the function like this:

`  EEG = clean_data_with_zapline_plus_eeglab_wrapper(EEG, struct('noisefreqs', 'line', 'plotResults', 0,  'winSizeCompleteSpectrum', floor(EEG.pnts/8/EEG.srate))); 
`

Any suggestions on what is wrong?

This is the output error:

```
Removing frequency artifacts using ZapLine with adaptations for automatic component selection and chunked data.
Computing initial spectrum...
"noisefreqs" parameter was set to 'line', found line noise candidate at 49.9725 Hz!
Searching for first noise frequency between 46.9725 and 52.9725Hz...
Removing noise at 49.9649Hz... 
Using adaptive chunk length!
Error using designfilt>parseAndDesignFilter
SWITCH expression must be a scalar or a character vector.

Error in designfilt (line 189)
  [err,requestedResponse,parseParams,h] = parseAndDesignFilter(inputParamValueNames, varargin{:});

Error in bandpass>designFilter (line 253)
opts.FilterObject = designfilt(params{:});

Error in bandpass (line 121)
    opts = designFilter(opts);

Error in clean_data_with_zapline_plus (line 356)
        data_narrowfilt = bandpass(data,[noisefreq-detectionWinsize/2 noisefreq+detectionWinsize/2],srate);

Error in clean_data_with_zapline_plus_eeglab_wrapper (line 25)
    [EEG.data, EEG.etc.zapline.config, EEG.etc.zapline.analyticsResults, plothandles] = clean_data_with_zapline_plus(EEG.data, EEG.srate, zaplineConfig);
```
 
 
 Thank you!

**Comment by schoffelen** [comment]
The error is probably due to a low-level non-robustness issue in the matlab bandpass.m function. I could not get this one to run on Linux (matlab 2023b, 2020b) or MacOS (matlab 2021a).

===========================

```
>> x=randn(1,10000);
>> y=bandpass(x,[20 40],250);
Error using designfilt>parseAndDesignFilter (line 519)
SWITCH expression must be a scalar or a character vector.

Error in designfilt (line 227)
  [err,requestedResponse,parseParams,h] = parseAndDesignFilter(inputParamValueNames, varargin{:});

Error in bandpass>designFilter (line 253)
opts.FilterObject = designfilt(params{:});

Error in bandpass (line 121)
    opts = designFilter(opts);
```

====================================

In other words, my recommendation at @MariusKlug would be to replace the call to bandpass with something more robust, otherwise the adaptive chuncklength will be useless

**Comment by MariusKlug** [comment]
Thank you for this find! It's unfortunate indeed. Until then a fixed chunk length of 30-60 seconds should be mostly OK and allow the main functionality of the toolbox at least...

**Comment by schoffelen** [comment]
Thanks. Yes, indeed your suggested fixed length is what I came up with for now.

**Comment by schoffelen** [comment]
Hi @MariusKlug, I must apologize, because it turns out that the cause of the reported error was sitting between the chair and the computer screen. I was sent off in the wrong direction of thinking that this were a low-level MATLAB error, due to the lack of information in the error stack. It now turns out that in my case (and I also suspect this to be the case for @NinaOmejc as well) I had an overloaded copy of the fir1.m file on my MATLAB-path, which was responsible for the SWITCH based error reported above. If I remove the folder with this overloaded m-file from my path, bandpass works as expected. My conclusion here is, that the issue can be closed here, and that we may need to consider updating the fir1.m version, that for instance lives in the fieldtrip repository, in fieldtrip/external/signal (i.e. the small folder that we use to overload signal-processing toolbox related functions)

**Comment by MariusKlug** [comment]
Oh snap, yeah overloading functions is the absolute bane of MATLAB toolboxes. Thanks for reporting and happy you found this!
